# Generated by Django 5.1.3 on 2024-11-28 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0006_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_management.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(unique=True),
        ),
    ]
